### ISSUE TITLE
Support for OpenAPI 3.1?

### ISSUE THREAD

**Issue by rberger** [lyra/openapi-dev-tool#13]
Any chance that support for OpenAPI 3.1 might be happening?

**Comment by gigaga** [comment]
Hi @rberger ,

In fact, OpenAPI Dev tool depends on several tools like:

- `redoc`
- `swagger UI`
- `swagger-parser`
- ...

The `swagger-parser` module used by OpenAPI Dev Tool prevented to support OpenAPI 3.1.0. I updated package and version of this module. Now, OpenAPI 3.1.0 is supported.
I published a new release for it : https://github.com/lyra/openapi-dev-tool/releases/tag/v9.7.0 ;)

Regards,

**Comment by rberger** [comment]
I presume you know, but swagger-ui (serving via swagger instead of redoc) can not yet support 3.1.0.

**Comment by gigaga** [comment]
You're right, Swagger UI is not OpenAPI 3.1 ready for now :(.
As you said, I advise you to use Redoc ;)
