### ISSUE TITLE
I can't get this to work, got error

### ISSUE THREAD

**Issue by dietergeerts** [lyra/openapi-dev-tool#18]
While evaluating tools for our API documentation and creation process, I tried this with our current swagger file, and can't get the `serve` to work. Then I tried with the official "pet store" spec, and that doesn't work either. I got the following error:

![image](https://user-images.githubusercontent.com/7393706/211546939-b61419d1-4bd6-420e-81df-8bc03685e652.png)

I was hoping to get this to work easily, but that doesn't seem to be the case, so I'm very hesitant to dive deeper into this tool(s) in order to see if we can use them. The thing is that a lot of peer dependencies are wrong, or are not correctly used, and with our rush/pnpm setup, they are checked, and thus I had to add lots of exclusions to install this package to begin with, which doesn't seem good Imho.

Another strange thing is that redoc doesn't support OpenAPI 3.1 yet, and is used here, while this project claims this support?

Some help is appreciated to further validate the usage of this tool.

**Comment by gigaga** [comment]
Hi @dietergeerts ,

To analyze your issue, I need you provide:

1. Your openapi specs file 
2. Your openapi-dev-tool config file
3. The version of openapi-dev-tool used

About OpenAPI 3.1 support, I confirm you that Redoc support OpenAPI 3.1 (basic) cf. https://github.com/Redocly/redoc

Regards,

**Comment by dietergeerts** [comment]
> 1. Your openapi specs file

I used the petstore one, both v2 and v3, to make sure the setup works first before trying our own.

> 2. Your openapi-dev-tool config file

```json
{
    "specs": [
        {
            "file": "./petstore.json",
            "context": {
                "version": "2.0",
                "public": "true"
            }
        }
    ]
}
```

> 3. The version of openapi-dev-tool used

`9.7.3`

But like mentioned I had to remove several peer dependencies due to errors when installing with pnpm. Now this file just removes the listing from the package file, so we don't get the errors, but they do point out that there is something wrong with the setup, and that the used packages are incompatible, and maybe in one of these is the reason of this bug?

```javascript
module.exports = {
    hooks: {
        readPackage(pkg, context) {
            if (pkg.name === 'ajv-oai') {
                context.log('Remove peer on ajv from ajv-oai');
                delete pkg.peerDependencies['ajv'];
            }
            if (pkg.name === 'mobx-react-lite') {
                context.log('Remove peer on mobx from mobx-react-lite');
                delete pkg.peerDependencies['mobx'];
            }
            if (pkg.name === 'mobx-react') {
                context.log('Remove peer on mobx from mobx-react');
                delete pkg.peerDependencies['mobx'];
            }
            if (pkg.name === 'redoc') {
                context.log('Remove peer on core-js from redoc');
                delete pkg.peerDependencies['core-js'];
                context.log('Remove peer on mobx from redoc');
                delete pkg.peerDependencies['mobx'];
                context.log('Remove peer on styled-components from redoc');
                delete pkg.peerDependencies['styled-components'];
            }
            return pkg;
        }
    }
}
```

**Comment by gigaga** [comment]
Hi @dietergeerts ,

Thanks for your feedback. I tried to reproduce your issue by using your configuration file but I can't do it. All works like a charm ;)

I think your main problem is that you removed some peer dependencies... When you install `openapi-dev-tool` by using, for example, `npm i -g @lyra-network/openapi-dev-tool`, there are several conflict messages, even if it is not great or beautiful, you shoudn't remove dependencies after installing. It is not blocking.

This warning messages are due to another dependency, indeed, for 13 months now, I am waiting for a PR on a dependency : [openapi-examples-validator](https://github.com/codekie/openapi-examples-validator/pull/158) :( . Without it, I have to find some workarounds...

Regards,
