### ISSUE TITLE
No way to merge a spec file before serving, without overwriting the input file

### ISSUE THREAD

**Issue by saschame** [lyra/openapi-dev-tool#4]
When merging and serving with a `config.json` (see below), the input .yml file gets overwritten with the merged .yml file.
Specifying a different output folder doesn't help, as the serve command then doesn't find the merged .yml spec.

**config.json**
```json
{
  "folder": "./specs",
  "output": "./specs",
  "specs": [
    {
      "file": "abc.yml"
    }
  ]
}
```

One way to solve this, I think, would be to be able to define different config files for merge and serve.
Or, have a config option in config.json to define a different folder, where the spec files are being served from.

PS also, there's a bug in `merge.js`, where `output` cannot be set in the config.json:
`const outputDir = getOutputDirFromConfig(config);` should be `const outputDir = getOutputDirFromConfig(config.config);`

PPS I sent a pull request for the bug in `merge.js`: https://github.com/lyra/openapi-dev-tool/pull/5

PPPS Great project, btw!

**Comment by gigaga** [comment]
Hi @saschame ,

thanks for your feedback 👍 
However, I don't understand what you're trying to do.

The "output" field in "config.json" doesn't exist.

**From serve command**

The merged file is in temporary working folder. This file is only computed to be provided to viewers (SwaggerUI / Redoc). You don't need to get it. 

**From merge command**

Sometimes, it could be interesting to get the merged file to share with someone or to be able to work on it from another tool. The "merge" command exists for that. In this case you have to specify your output directory in command line of "merge" command as explained in https://github.com/lyra/openapi-dev-tool#usage-2

For example, from your config.json
```json
{
  "folder": "./specs",
  "specs": [
    {
      "file": "abc.yml"
    }
  ]
}
``` 

After `openapi-dev-tool merge --output outputDir`, the merged file will be present in <outputDir> folder.

**Comment by saschame** [comment]
Oops, sorry. 🙈
I'm splitting a spec file and had (or still have) errors, when splitting paths into their own .yaml files.
With schemas, this works fine but as soon as I put paths or responses into their own .yaml files, I get erros:
```
The API is invalid: Token "components" does not exist.
```

After that, I started to look into a lot of wrong directions, to mitigate the problem.

**Comment by gigaga** [comment]
No problem ;)
FYI, "$ref" cannot be used anywhere in your yaml/json files (https://swagger.io/docs/specification/using-ref/). For example :

You can't do :
```yaml
openapi: '3.0.0'
...
paths:
    $ref: 'path.yaml'
```

But you can do :
```yaml
openapi: '3.0.0'
...
paths:
  /users:
    $ref: '../resources/users.yaml'
  /users/{userId}:
    $ref: '../resources/users-by-id.yaml'
```

Regards,
