### ISSUE TITLE
Remove deprecated redoc-pro

### ISSUE THREAD

**Issue by RomanHotsiy** [lyra/openapi-dev-tool#9]
Hey there! Good job on this dev tool.

I noticed it uses `@redoc/redoc-pro` package which we deprecated just recently.

This package is not open-source and was distributed under commercial license so could you please remove it from this package?

**Comment by gigaga** [comment]
Hi @RomanHotsiy ,

ugh ! Ok, I'm going to remove it :)

Thx

**Comment by gigaga** [comment]
It's done with https://github.com/lyra/openapi-dev-tool/commit/0965c9d5ea6c0679ab6713feee2fcfbf127decf0

**Comment by RomanHotsiy** [comment]
Thanks a lot for the quick response! 🙌
